version: "3.8"

services:
  opengl-dev:
    build: .
    container_name: opengl-development
    volumes:
      - ./src:/workspace/src
      - ./build:/workspace/build
      - ./examples:/workspace/examples
      - ./Makefile:/workspace/Makefile
      - ./build.sh:/workspace/build.sh
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY:-:0}
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /workspace

    # For Windows users with VcXsrv or similar X server
    # Uncomment the following lines if you're using Windows with an X server
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # environment:
    #   - DISPLAY=host.docker.internal:0.0
